# .terraform-docs.yml

formatter: "markdown table"
settings:
  color: true
content: |-
  {{ .Header }}
  {{ include "examples/description.md" }}
  
  {{ .Requirements }}

    ## How to use this module
    ### With tfvars file.
    {{ include "examples/example-1/description.md" }}
    
    #### main.tf
    ```hcl
    {{ include "examples/example-1/main.tf" }}
    ```
    #### variables.tf
    ```hcl
    {{ include "examples/example-1/variables.tf" }}
    ```
    #### terraform.tfvars
    ```hcl
    {{ include "examples/example-1/terraform.tfvars" }}
    ```

    ### Directly
    #### Main.tf
    ```hcl
    {{ include "examples/example-2/main.tf" }}
    ```

  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Modules }}
  {{ .Footer }}

recursive:
  enabled: false

output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true
